config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users

  root 'meetings#index'
  resources :rooms
  resources :meetings

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  default_scope { order(scheduled_at: :asc) }
  belongs_to :user
  belongs_to :room

  validates :title, :day, :scheduled_at, presence: true
  validates_inclusion_of :scheduled_at, in: 8..18
  validates :scheduled_at, uniqueness: true, if: :uniqueness_by_user?
  validates_associated :room

  def start_time
    day
  end

  protected

  def identical_meeting
    Room.joins(:meetings).where(
      "
        rooms.name = ? AND
        meetings.user_id != ? AND
        meetings.day = ? AND
        meetings.scheduled_at = ?",
      room.name,
      user.id,
      day,
      scheduled_at
    ).exists?
  end

  def uniqueness_by_user?
    if room.present? && user.present? && title.present? && day.present? && scheduled_at.present? && !identical_meeting
      false
    else
      true
    end
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  default_scope { order(created_at: :desc) }
  has_many :meetings, autosave: true, dependent: :destroy
  validates :name, presence: true

  after_create_commit { broadcast_prepend_to "rooms" }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  has_many :meetings, autosave: true, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_action_cable_identifier

  private

  def set_action_cable_identifier
    cookies.encrypted[:user_id] = current_user&.id
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  def index
    date_to_start = params[:start_date].blank? ? Date.today.beginning_of_month : params[:start_date].to_date.beginning_of_month
    date_to_end = date_to_start.end_of_month
    @meetings = Meeting.where('day between ? and ?', date_to_start, date_to_end).all
    @meeting = Meeting.new
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)
    @meeting.save
    redirect_to(meetings_path)
  end

  def edit
    render(action: :index)
  end

  def update
    @meeting = current_user.meetings.find(params[:id])
    @meeting.update(meeting_params)

    redirect_to(meetings_path)
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :room_id, :user_id, :day, :scheduled_at)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, :only_if_exists, only: %i[edit update destroy]
  before_action :set_rooms, only: %i[edit index]

  def index
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    redirect_to(rooms_path)
  end

  def edit
    render(action: :index)
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)

    redirect_to(rooms_path)
  end

  def destroy
    @room.destroy
    redirect_to(rooms_path)
  end

  private

  def set_rooms
    @rooms = Room.all
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def only_if_exists
    redirect_to(rooms_path) unless @room.present?
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  def short_meeting_title(meeting)
    "#{l(meeting.day, format: :short)} as #{meeting.scheduled_at}h - #{meeting.title.truncate(14)}"
  end

  def long_meeting_title(meeting)
    "Room: #{meeting.room.name} created by #{meeting.user.email} at #{l(
      meeting.day,
      format: :short
    )} as #{meeting.scheduled_at}h - #{meeting.title.truncate(14)}"
  end
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

module MeetingsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="row mb-4">
    <div class="col-md-12">
      <h5>
        <%= I18n.t("errors.messages.not_saved",
                  count: resource.errors.count,
                  resource: resource.class.model_name.human.downcase)
        %>
      </h5>
      <% resource.errors.full_messages.each do |message| %>
        <div class="badge badge-secondary"><%= message %></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetingsToMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container h-100">
      <div class="row mt-4 justify-content-center align-items-center">
        <div class="col-12">
          <h2 id="application_title">Meetings to Me
          <% if user_signed_in? %>
            <small><%="Hello #{current_user.email}" %> (<span id="<%="count-meetings-#{current_user.id}"%>"><%=current_user.meetings.count%> meetings</span>)</small>
          <% end %>
          </h2>
          <div class="btn-group mt-2" role="group" aria-label="Application Actions">
            <%= link_to "Dashboard/Create Meeting", root_path, class:"btn btn-primary" %>
            <%= link_to "Create Room", rooms_path, class:"btn btn-secondary" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-secondary" if user_signed_in? %>
          </div>
          <hr />
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: global_meetings do |date, meetings| %>
  <%= date %><br />
  <% meetings.each do |meeting| %>
    <%= render partial: 'calendar_cell', locals: {meeting: meeting} %>
  <% end %>
<% end %>

app/views/meetings/_calendar_cell.html.erb
<a class="badge badge-success" href="javascript:void(0)" title="<%= long_meeting_title(meeting) %>">
  <%= short_meeting_title(meeting) %>
</a>

app/views/meetings/_form.html.erb
<%= form_with model: meeting do |f| %>
  <%= render "layouts/error_messages", resource: meeting %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :room_id, class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.select :room_id, Room.all.collect {|r| [ r.name, r.id ] }, { prompt: 'Select a Room' }, { style: 'width: 100%', class: 'form-control', required: true } %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :title, class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_field :title, class: 'form-control', placeholder: 'title...', required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= label_tag :day, "Date", class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.date_select :day, {}, { class: 'form-control', style: 'width: auto; display: inline' } %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :scheduled_at, class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.select :scheduled_at, (8..18).to_a, { prompt: 'Select the hour'},  { class: 'form-control d-inline', style: 'width: auto' } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary btn-save-meeting" %>
      </div>
    </div>
  </div>
<% end %>

app/views/meetings/index.html.erb
<h5>Dashboard for Meetings</h5>

<div id="<%="form-meetings-#{current_user.id}"%>">
  <%= render partial: 'form', locals: {meeting: @meeting} %>
</div>
<div id="calendar">
  <%= render partial: "calendar", locals: {global_meetings: @meetings} %>
</div>

app/views/rooms/_form.html.erb
<%= form_with model: room, local: true, html: {class: "my-4"} do |form| %>
  <div class="form-group">
    <%= form.text_field :name, placeholder: "Enter with the name of room", class: "form-control", required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="card mb-2 bg-light">
  <div class="card-body">
    <h4 class="card-title text-muted">
      <%= room.name %>
      <small>-- <%=time_ago_in_words room.created_at %></small>
    </h4>
    <p class="card-text lead">
      <%= link_to 'Edit', edit_room_path(room), class: "btn btn-secondary" %>
      <%= button_to 'Destroy', room_path(room), method: :delete, class: "btn btn-danger" %>
    </p>
  </div>
</div>

app/views/rooms/index.html.erb
<h5>Dashboard for Rooms</h5>

<%= render partial: 'form', locals: { room: @room } %>
<%= turbo_stream_from "rooms" %>
<%= turbo_frame_tag "rooms" do %>
  <%= render partial: "room", collection: @rooms %>
<% end %>

app/views/simple_calendar/_month_calendar.html.erb
<hr />
<div class="simple-calendar">
  <h5>Calendar to month: <%= start_date.all_month %></h5>
  <div class="calendar-heading mb-2">
    <%= link_to t('simple_calendar.previous', default: 'Previous month'), calendar.url_for_previous_view, class: 'btn btn-secondary' %>
    <%= link_to t('simple_calendar.next', default: 'Next month'), calendar.url_for_next_view, class: 'btn btn-secondary' %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day), id: "date-#{day}" do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>